<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-21T12:28:50 IST" name="Default Suite" finished-at="2022-09-21T12:28:50 IST" duration-ms="372">
    <groups>
    </groups>
    <test started-at="2022-09-21T12:28:50 IST" name="ProjectForReview" finished-at="2022-09-21T12:28:50 IST" duration-ms="372">
      <class name="com.test.TestMainCrud">
        <test-method is-config="true" signature="setUpH2Connection()[pri:0, instance:com.test.TestMainCrud@16267862]" started-at="2022-09-21T12:28:50 IST" name="setUpH2Connection" finished-at="2022-09-21T12:28:50 IST" duration-ms="197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpH2Connection -->
        <test-method signature="testByID()[pri:0, instance:com.test.TestMainCrud@16267862]" started-at="2022-09-21T12:28:50 IST" name="testByID" finished-at="2022-09-21T12:28:50 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testByID -->
        <test-method is-config="true" signature="setUpH2Connection()[pri:0, instance:com.test.TestMainCrud@16267862]" started-at="2022-09-21T12:28:50 IST" name="setUpH2Connection" finished-at="2022-09-21T12:28:50 IST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpH2Connection -->
        <test-method signature="testByName()[pri:0, instance:com.test.TestMainCrud@16267862]" started-at="2022-09-21T12:28:50 IST" name="testByName" finished-at="2022-09-21T12:28:50 IST" depends-on-methods="com.test.TestMainCrud.testByID" duration-ms="46" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [tiya] but found [Krishna],
expected [piya] but found [Somani]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [tiya] but found [Krishna],
expected [piya] but found [Somani]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.test.TestMainCrud.testByName(TestMainCrud.java:73)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testByName -->
      </class> <!-- com.test.TestMainCrud -->
    </test> <!-- ProjectForReview -->
  </suite> <!-- Default Suite -->
</testng-results>
